version: '3.8'

services:
  api:
    build: .
    container_name: hr-system
    command:  >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py loaddata hr_fixture.json &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/
    ports:
      - 8004:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: hr-system-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
volumes:
  postgres_data:
